---
title: "GCP Data Management"
author: "Doug Tommet"
date: '`r Sys.Date()`'
params:
  pull_from_googlesheets: TRUE
output:
  html_document:
    keep_md: yes
    toc: yes
    toc_float: yes
    theme: cerulean
  word_document: default
---



```{r, echo=FALSE, message=FALSE, warning=FALSE}
source(here::here("R", "001-Libraries_and_functions.R"))
source(here::here("R", "005-Folder_paths_and_options.R"))

```


```{r, eval = FALSE, echo=FALSE, message=FALSE, warning=FALSE}

source(here::here("R", "010-Read_data.R"))

# GCPv1: Didn't fix mistakes, Animal/Supermarket linked, CFL/FAS linked
gcp_version <- "GCPv1"
saveRDS(gcp_version, file=path(r_objects_folder, "000_gcp_version.rds"))
source(here::here("R", "020-Transform_data.R"))
source(here::here("R", "021-Missing_values.R"))

source(here::here("R", "023-Item_recoding.R"))
source(here::here("R", "024-Data_to_long.R"))
# source(here::here("R", "031-Frogger_plot.R"))
# source(here::here("R", "050-Item_management.R"))
source(here::here("R", "060-Study_linkage_setup.R"))
source(here::here("R", "070-Create_linking_object.R"))
source(here::here("R", "090-link_studies.R"))
source(here::here("R", "091-link_studies_2.R"))
source(here::here("R", "095-create_linking_summary_Rmds.R"))

# GCPv2a: Fix mistakes, Animal/Supermarket linked, CFL/FAS linked
gcp_version <- "GCPv2a"
saveRDS(gcp_version, file=path(r_objects_folder, "000_gcp_version.rds"))
source(here::here("R", "020-Transform_data.R"))
source(here::here("R", "021-Missing_values.R"))

source(here::here("R", "023-Item_recoding.R"))
source(here::here("R", "024-Data_to_long.R"))
# source(here::here("R", "031-Frogger_plot.R"))
# source(here::here("R", "050-Item_management.R"))
source(here::here("R", "060-Study_linkage_setup.R"))
source(here::here("R", "070-Create_linking_object.R"))
source(here::here("R", "090-link_studies.R"))
source(here::here("R", "091-link_studies_2.R"))
source(here::here("R", "095-create_linking_summary_Rmds.R"))
                        
# GCPv2b: Fix mistakes, Animal/Supermarket not linked, FAS separate (F linked to F)
gcp_version <- "GCPv2b"
saveRDS(gcp_version, file=path(r_objects_folder, "000_gcp_version.rds"))
source(here::here("R", "020-Transform_data.R"))
source(here::here("R", "021-Missing_values.R"))

source(here::here("R", "023-Item_recoding.R"))
source(here::here("R", "024-Data_to_long.R"))
# source(here::here("R", "031-Frogger_plot.R"))
# source(here::here("R", "050-Item_management.R"))
source(here::here("R", "060-Study_linkage_setup.R"))
source(here::here("R", "070-Create_linking_object.R"))
source(here::here("R", "090-link_studies.R"))
source(here::here("R", "091-link_studies_2.R"))
source(here::here("R", "095-create_linking_summary_Rmds.R"))

# GCPv2c: Fix mistakes, Animal/Supermarket not linked, CFL/FAS not linked
gcp_version <- "GCPv2c"
saveRDS(gcp_version, file=path(r_objects_folder, "000_gcp_version.rds"))
source(here::here("R", "020-Transform_data.R"))
source(here::here("R", "021-Missing_values.R"))

source(here::here("R", "023-Item_recoding.R"))
source(here::here("R", "024-Data_to_long.R"))
# source(here::here("R", "031-Frogger_plot.R"))
# source(here::here("R", "050-Item_management.R"))
source(here::here("R", "060-Study_linkage_setup.R"))
source(here::here("R", "070-Create_linking_object.R"))
source(here::here("R", "090-link_studies.R"))
source(here::here("R", "091-link_studies_2.R"))
source(here::here("R", "095-create_linking_summary_Rmds.R"))

source(here::here("R", "200-check_and_save_itembank.R"))
source(here::here("R", "250-item_information.R"))
source(here::here("R", "400-score_gcp.R"))

```

```{r, child='002-Opening_statement.Rmd'}
```

```{r, child='010-Read_data.Rmd'}
```

```{r, child='020-Transform_data.Rmd'}
```

```{r, child='021-Missing_values.Rmd'}
```

```{r, child='023-Item_recoding.Rmd'}
```

```{r, child='024-Data_to_long.Rmd'}
```

# Summary of item linking under GCPv1

```{r, child='101-link-HRS_ADAMS_GCPv1.Rmd'}
```

```{r, child='102-link-SAGES_GCPv1.Rmd'}
```

```{r, child='103-link-SAGESII_Inperson_GCPv1.Rmd'}
```

```{r, child='104-link-SAGESII_Telephone_GCPv1.Rmd'}
```

```{r, child='105-link-SAGESII_Video_GCPv1.Rmd'}
```

```{r, child='106-link-SAGES_Telephone_GCPv1.Rmd'}
```

```{r, child='107-link-INTUIT_ACTIVE_GCPv1.Rmd'}
```

# Summary of item linking under GCPv2a

```{r, child='101-link-HRS_ADAMS_GCPv2a.Rmd'}
```

```{r, child='102-link-SAGES_GCPv2a.Rmd'}
```

```{r, child='103-link-SAGESII_Inperson_GCPv2a.Rmd'}
```

```{r, child='104-link-SAGESII_Telephone_GCPv2a.Rmd'}
```

```{r, child='105-link-SAGESII_Video_GCPv2a.Rmd'}
```

```{r, child='106-link-SAGES_Telephone_GCPv2a.Rmd'}
```

```{r, child='107-link-INTUIT_ACTIVE_GCPv2a.Rmd'}
```

# Summary of item linking under GCPv2b

```{r, child='101-link-HRS_ADAMS_GCPv2b.Rmd'}
```

```{r, child='102-link-SAGES_GCPv2b.Rmd'}
```

```{r, child='103-link-SAGESII_Inperson_GCPv2b.Rmd'}
```

```{r, child='104-link-SAGESII_Telephone_GCPv2b.Rmd'}
```

```{r, child='105-link-SAGESII_Video_GCPv2b.Rmd'}
```

```{r, child='106-link-SAGES_Telephone_GCPv2b.Rmd'}
```

```{r, child='107-link-INTUIT_ACTIVE_GCPv2b.Rmd'}
```

# Summary of item linking under GCPv2c

```{r, child='101-link-HRS_ADAMS_GCPv2c.Rmd'}
```

```{r, child='102-link-SAGES_GCPv2c.Rmd'}
```

```{r, child='103-link-SAGESII_Inperson_GCPv2c.Rmd'}
```

```{r, child='104-link-SAGESII_Telephone_GCPv2c.Rmd'}
```

```{r, child='105-link-SAGESII_Video_GCPv2c.Rmd'}
```

```{r, child='106-link-SAGES_Telephone_GCPv2c.Rmd'}
```

```{r, child='107-link-INTUIT_ACTIVE_GCPv2c.Rmd'}
```







```{r, child='999-R_session_info.Rmd'}
```
